name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    env:
      OUTPUT_BINARY: sshg
      GO_VERSION: 1.23.3

    steps:
      - uses: actions/checkout@v3
      - name: Load VERSION
        run: |
          if [ -f VERSION ]; then
            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          else
            echo "VERSION file not found!" && exit 1
          fi
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: |
          CGO_ENABLED=0 go build -o  ${{ env.OUTPUT_BINARY }}-${{matrix.goos}}-${{matrix.goarch}} ./main.go
      - name: Package
        run: |
          tar -czvf ${{ env.OUTPUT_BINARY }}-${{matrix.goos}}-${{matrix.goarch}}.tar.gz ./${{ env.OUTPUT_BINARY }}-${{matrix.goos}}-${{matrix.goarch}}
      - name: Upload to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_BINARY }}
          path: |
            ./${{ env.OUTPUT_BINARY }}*
      - name: 上传至Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.VERSION }}
          artifacts: ./${{ env.OUTPUT_BINARY }}*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.VERSION }}
          allowUpdates: true
        env:
          export PATH: $PATH:/usr/local/go/bin     
